language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

before_install:
- sudo apt-get install -y pandoc

install:
  # Install this package and the packages listed in requirements.txt.
  - pip install -v .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

env:
  global:
    # Doctr deploy key for PAHdb/AmesPAHdbPythonSuite
    - secure: "Jzxgq6DRbdAHusBdP8RVLR+yaw4zxiYAx+gKFZ+YIAQThSrTxIJsuSVpvgDhJYhYCakTdzXssQxmzPaFDwMNlp+cVNtKIGssi4OR6NRPm0Ws9H9U0FNShyVpV9n8KflGigr5ZJZjgfDYFzpiSwaLnnDgGOXm0bnAYWs6OyX8KTu3DfrByPtSVZf6d9X7UAIJxttQGHUhMNla305TGE9mGHAzPgwc8lYRm6ZWxDGPACCIPXLRav3CL3ktApncZnp1EpjNVr3/fgJCXOVr2ggNs1d8aDIYjjiKW7FfWUHndEUkdaZnoOkagixE45+rKzPyegeBijfLK80jFq6pfO+Lk26MJHXrwnDXMAKHxHjqYnBpmPsbk28+2bTSyTK8+DnnJE0iMBD/4SKyxm4ND4CiM2QnGWGgtoC/q8KCXf13HihUbrcyj3NxnEvR8lb3Qbz5sf+5CRw12WWiAm1HWBK8vuAn8GOknijX9+4bt8ZINCdlBSnb+F9JJcyEhlJKOWIcSiFTbLAAjMHPNVCwWiayZvkb7todUpHyMCqWHpuRic2Z1KBEiqQhZUK2/GWg5i0rxX/7j9tsK5VNSuYVnjOjKp+7dgjwGew3zU2rz94Q4BIYekipOZcwrT1xLUt4B45jq6TxIVIv+sk8W7Y4HZbqFToAe6uYE5LWj8fTKoNOnbo="

script:
  - cd  # Change path to $HOME.
  - coverage run --source amespahdbpythonsuite --omit *amespahdbpythonsuite/_version.py,*amespahdbpythonsuite/tests/* -m pytest --pyargs amespahdbpythonsuite.tests  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - cd $TRAVIS_BUILD_DIR  # Change path back to $TRAVIS_BUILD_DIR.
  - flake8 --exclude versioneer.py,amespahdbpythonsuite/utils/token_utils.py  # Enforce code style.
  - make -C docs html  # Build the documentation.
  - set -e
  - doctr deploy --built-docs docs/build/html .  # Publish the documentation.
